//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class commune
    {
        public string commune_id { get; set; }
        public string commune_name { get; set; }
        public Nullable<int> degree { get; set; }
        public string district_id { get; set; }
    
        public virtual district district { get; set; }
    }
}
